# Generated by Django 5.1.4 on 2024-12-29 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la temporada', max_length=100)),
                ('descripcion', models.TextField(help_text='Ingrese una descripción de la temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del producto', max_length=100)),
                ('descripcion', models.TextField(help_text='Ingrese una descripción del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Ingrese el precio del producto', max_digits=10)),
                ('stock', models.PositiveIntegerField(help_text='Ingrese la cantidad disponible del producto')),
                ('imagen', models.ImageField(blank=True, help_text='Seleccione una imagen para el producto', null=True, upload_to='productos')),
                ('temporada', models.ForeignKey(help_text='Seleccione la temporada del producto', on_delete=django.db.models.deletion.CASCADE, to='comercio.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(help_text='Ingrese el número de celular del vendedor', max_length=50)),
                ('avatar', models.ImageField(blank=True, help_text='Seleccione una imagen de perfil para el vendedor', null=True, upload_to='imagenes_perfil')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado al vendedor', on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la venta')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad vendida')),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, help_text='Precio total de la venta', max_digits=10)),
                ('producto', models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.PROTECT, to='comercio.producto')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vendedor que realizó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercio.vendedor')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
