# Generated by Django 5.1.4 on 2024-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='celular',
            field=models.CharField(blank=True, help_text='Ingrese el número de celular del vendedor', max_length=50, null=True),
        ),
    ]
