# Generated by Django 5.1.3 on 2024-12-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_alter_vendedor_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
    ]
