# Generated by Django 5.1.4 on 2024-12-31 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_remove_venta_cantidad_remove_venta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(help_text='Producto vendido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='comercio.producto'),
        ),
    ]
