# Generated by Django 5.1.4 on 2025-01-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_venta_cantidad_venta_producto'),
        ('comercio', '0005_venta_cantidad'),
    ]

    operations = [
    ]
